name: EnderDragonHunt
main: com.plugin.ftb.enderdragonhunt.Main
version: 1.0
commands:
  enderdragon:
    usage:  /<command>
    permission: enderdragonhunt.command
    
permissions:
  enderdragonhunt.command:
    default: op
depend:
  - ProtocolLib
