name: EnderDragonHunt
main: com.plugin.ftb.enderdragonhunt.Main
version: 1.0
commands:
  enderdragon:
    usage:  /<command>
    permission: enderdragonhunt.command
  ftb28:
    usage:  /<command>
    default: true
  desert:
    usage:  /<command>
    default: true
  end:
    usage:  /<command>
    default: true
  nether:
    usage:  /<command>
    default: true
  portal:
    usage:  /<command>
    default: true
    
permissions:
  enderdragonhunt.command:
    default: op
depend:
  - ProtocolLib
